{% set name = "liknorm-py" %}
{% set version = "1.0.13" %}
{% set sha256 = "c478b032768e8c8382f6ef3880ef4c9ddabae188099c65104430d90269353f1e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: liknorm-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/liknorm/liknorm-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - cffi >=1.8
    - toolchain
    - liknorm >=1.3.11
  run:
    - python
    - cffi >=1.8
    - liknorm >=1.3.11
    - numpy >=1.10

test:
  requires:
    - pytest >=3
    - pytest-pep8
    - pytest-sugar
  imports:
    - liknorm
  commands:
    - python -c "import sys; import liknorm; sys.exit(liknorm.test())"

about:
  home: https://github.com/limix/liknorm-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Liknorm Python wrapper'
  doc: https://github.com/limix/liknorm-py
  dev_url: https://github.com/limix/liknorm-py

extra:
  recipe-maintainers:
    - Horta
