{% set name = "liknorm-py" %}
{% set version = "1.0.9" %}
{% set sha256 = "2605da9454aaa9195a3701648f96e173d6f82aefe81e8681b49693b9ac672c64" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: liknorm-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/liknorm/liknorm-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - cffi >=1.8
    - toolchain
    - liknorm >=1.3.7
  run:
    - python
    - cffi >=1.8
    - liknorm >=1.3.7
    - numpy >=1.10

test:
  requires:
    - pytest >=3
    - pytest-pep8
    - pytest-sugar
  imports:
    - liknorm
  commands:
    - python -c "import sys; import liknorm; sys.exit(liknorm.test())"

about:
  home: https://github.com/limix/liknorm-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Liknorm Python wrapper'
  doc: https://github.com/limix/liknorm-py
  dev_url: https://github.com/limix/liknorm-py

extra:
  recipe-maintainers:
    - Horta
