{% set name = "liknorm-py" %}
{% set variant = "openblas" %}
{% set version = "1.2.2" %}
{% set sha256 = "6099eb01d394cbdc09af1b5a6b9817074c58341ce7c0cda1074ae5813f574bfc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: liknorm-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/liknorm/liknorm-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - blas 1.1 {{ variant }}    # [not win]
    - cffi
    - liknorm >=1.5.1
    - numpy
    - openblas                  # [not win]
    - pip
    - pytest-runner
    - python
    - setuptools
  run:
    - blas 1.1 {{ variant }}    # [not win]
    - cffi
    - liknorm >=1.5.1
    - openblas                  # [not win]
    - pytest
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - liknorm
  commands:
    - python -c "import sys; import liknorm; sys.exit(liknorm.test())"

about:
  home: https://github.com/limix/liknorm-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Liknorm Python wrapper'
  doc_url: https://github.com/limix/liknorm-py
  dev_url: https://github.com/limix/liknorm-py

extra:
  recipe-maintainers:
    - Horta
