{% set name = "liknorm-py" %}
{% set version = "1.2.6" %}
{% set sha256 = "f119b6439ff75adb6c5a1df8ff9a69526fd8bd9c00b4ccbbce3b8b65dfd1f77a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: liknorm-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/liknorm/liknorm-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cffi
    - liknorm >=1.5.6
    - pip
    - python
    - setuptools
  run:
    - cffi
    - liknorm >=1.5.6
    - python

test:
  imports:
    - liknorm
  requires:
    - pytest
    - numpy
  commands:
    - python -c "import sys; import liknorm; sys.exit(liknorm.test())"

about:
  home: https://github.com/limix/liknorm-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Liknorm Python wrapper
  doc_url: https://github.com/limix/liknorm-py
  dev_url: https://github.com/limix/liknorm-py

extra:
  recipe-maintainers:
    - Horta
