{% set name = "liknorm-py" %}
{% set version = "1.0.6" %}
{% set sha256 = "abaefb871fc97a034d992deaa427a7ce1a6bcb72c26ae0cb56eb2e383e8fff8b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win32 or linux32 or (win64 and py27)]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cffi >=1.7
    - toolchain
    - liknorm >=1.2.6
  run:
    - python
    - cffi >=1.7
    - liknorm >=1.2.6
    - numpy >=1.10

test:
  requires:
    - pytest >=3
  imports:
    - liknorm
  commands:
    - python -c "import sys; import liknorm; sys.exit(liknorm.test())"

about:
  home: https://github.com/limix/liknorm-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Liknorm Python wrapper'
  doc: https://github.com/limix/liknorm-py
  dev_url: https://github.com/limix/liknorm-py

extra:
  recipe-maintainers:
    - Horta
