{% set name = "liknorm-py" %}
{% set version = "2.0.0" %}
{% set sha256 = "4bde18cb4f536a03163046df8ab7e55e8a06dc565f9711a431506106d8638879" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: liknorm-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/liknorm/liknorm-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cffi
    - liknorm >=1.5.6
    - pip
    - python
    - setuptools
  run:
    - cffi
    - liknorm >=1.5.6
    - python

test:
  imports:
    - liknorm
  requires:
    - pytest
    - numpy
  commands:
    - python -c "import sys; import liknorm; sys.exit(liknorm.test())"

about:
  home: https://github.com/limix/liknorm-py
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Liknorm Python wrapper
  doc_url: https://github.com/limix/liknorm-py
  dev_url: https://github.com/limix/liknorm-py

extra:
  recipe-maintainers:
    - Horta
