# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "UpZEBxjjsJ3e/9Cn+ePcWlPYuuIX6wlZxtt9L4xkZ33R32/I8O28N69jVvHycKlYKTuwT/jmzSBXxwm8Y88YCDU9Ad8yldQsSST6HX43/D5Pq1C5nKnU9s8P0bSnUQeFQCsziOYH5Hqj5HmxjPTs5AWQ8cdXpvcfpEeUYMyV1Utk8fqqKdv4dgz26j/eHxZ31ylhTXKOIum2yrZBsDgketvRw3r1hl/Bg/mL9mdoHZTpUp3Oo3f0uC6ev6hLkR86encyqAVP+HOWspp0sPJ7Jlnl2YKakY0jLpbLWPpzVvzxWRSTyGgtWNZI1ziTH4Jwt5B+olpnC7rhwn9VLj0VGGSycGca9KXiN91sfXrVhnqswTdDLixLqt8Td/qLLt6wWg+i8YVPFoawu9mi/y/neMf66lKpGF74Npb0DBdA8lOvQ5OkjMSUXlXVqLMmxrRRst90JJP9uSOihShm9qqhYB+k7SoKYqYqt2OKHQhi79FARPlJ1wFt5pBx9Q12k3JRzcrFChvBftuHeWgoA4GvBEQE6670cRwQcIaVijLALilRikqzHOvDW1aUIcBMUiP6aZkVuS5Ep+8H5lQup1V6G2PGf6fpEKwOs1MOPAoAxhxkimXAd51iyy5qk92WUgTvi7ZyR5UilSz7jFwOHy7igS+Z9SfDltFvNHSD/i9oeYs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
