travis:
  secure:
    BINSTAR_TOKEN: egatrhilgWnNlXIR+l1JsKCfDlLFjB6wbSqjeMdETwfgQ3HETrjtj+kBYfocXKQm/f/Ha/FTITQnKj2txGkLJqguyjNkkm9lnjR7NN5gIaUJH8pEBIGvCkefa6O0dh6IiHdPAtPnjLpFSzbWLEOjFlv9QBn8YymR0n0vi1B2hk8UFr1bPfheRtMoA/qPoIXtW/iCzez05n6gJyhSJYnkj3xfhKxA+hvLYh+EvDmuBJlPvJPSsYHMwvLXRVoNX2LpHAk09RnMjXKMq96IPcPlWqR5/FgpZWjo38jOcxpY5qHzPKtwiDUUeh7xdYYXv9k5b+ghvuuScZRgFe8gBc2DvxBRx2BOjEB2lyX0eSJxWVAFz0XUWngmyxJYO0m6Du0yCAex3FDBaduWv7+RXM5VZKNmy7KnuRSE02DdZGT2wMRIcCoCmpkW3SqyyyblCxRhC5lgS+f1h7K6XOpGF1X4lsmjNy79A/lTxNFG+TNNIWlX4QqU8tJx/JLAGLS2FlHwuzcBAG9bnuSnSJ0hSo6QwXyPictitz2M4zSaxAaWnjS6ATMbp5Hd2m+T8/mbreki92VlZOrNea8Tn/B+jFiQKrr24WkAdAGWKR4o1wAeWwYHip2T/F50rocjCifugZvpo+pRpJTQewfHVSLx7SSAcpIZM8HWeOhSWAlrUF3sFlU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
